server:
  port: 8181
  redis:
    host: 172.19.45.229
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8     # 最大连接数
        max-idle: 4       # 最大空闲连接
        min-idle: 1       # 最小空闲连接
        max-wait: 2000ms  # 获取连接最大等待时间
    timeout: 5000ms      # 连接超时时间